locanor_site:
    resource: "@LocanorSiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
  path: /login
  defaults:
   _controller: LocanorUserBundle:Security:login

login_check:
  path: /login_check


logout:
  path: /logout
